org.gradle.jvmargs=-Xmx1536m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.workers.max=2
kotlin.incremental=false

systemProp.java.net.preferIPv4Stack=true
android.builder.sdkDownload=false
# Avoid flaky D8 DexingWithClasspathTransform on kotlin-stdlib (AGP 7.4)
android.useFullClasspathForDexingTransform=true

